### PR TITLE
20 setup-linting-andor-autoformatting-for-frontend

### PR DESCRIPTION
**Pull request by BadhonRahman01**
I installed and configured Eslint for formatting and linting for this project.

### CODE REVIEW

**Comment by tuomasmustakallio** [comment]
This doesn't have unified linting/autoformatting configuration as stated in the ticket acceptance criteria ?

**Review by KeManen — CHANGES_REQUESTED** [review]
Let's add linting and prettier to the frontend pipeline.

**Review by OttoAhlfors — COMMENTED** [review]
"indent": ["error", 2], could this be 4 
    "semi": ["error", "always"],  and could we not have semicolons

**Review by KeManen — COMMENTED** [review]
The pipeline now works. Lets get this merged when the lint issues are fixed.

**Review by KeManen — APPROVED** [review]

**Review by OttoAhlfors — APPROVED** [review]

**Pull request merged**
